name:  Bug Report
description: Reporta un bug para ayudarnos a mejorar IssueFlow
title: "[Bug]: "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        隆Gracias por tomarte el tiempo de reportar un bug! 
        
        Por favor completa la informaci贸n a continuaci贸n para ayudarnos a reproducir y solucionar el problema.

  - type: input
    id: version
    attributes:
      label: Versi贸n de IssueFlow
      description: 驴Qu茅 versi贸n de IssueFlow est谩s usando?
      placeholder: "0.1.0"
    validations:
      required: true

  - type: dropdown
    id: framework
    attributes:
      label: Framework
      description: 驴En qu茅 framework est谩s usando IssueFlow?
      options:
        - React
        - Vue
        - Next.js
        - Nuxt
        - Astro
        - WordPress
        - Vanilla JS
        - Otro
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Descripci贸n del Bug
      description: Una descripci贸n clara y concisa del problema
      placeholder: Describe qu茅 est谩 pasando y qu茅 esperabas que pasara
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Pasos para Reproducir
      description: Pasos para reproducir el comportamiento
      placeholder: |
        1. Ir a '...'
        2. Click en '...'
        3. Hacer scroll hacia '...'
        4. Ver error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Comportamiento Esperado
      description: Una descripci贸n clara de lo que esperabas que pasara
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots/Videos
      description: Si es aplicable, agrega screenshots para ayudar a explicar el problema

  - type: textarea
    id: environment
    attributes:
      label: Entorno
      description: |
        Ejemplos:
          - OS: macOS Big Sur 11.2.3
          - Browser: Chrome 89.0.4389.82
          - Node.js: 16.14.0
          - Package Manager: npm 8.5.0
      value: |
        - OS: 
        - Browser: 
        - Node.js: 
        - Package Manager: 
      render: markdown

  - type: textarea
    id: additional
    attributes:
      label: Contexto Adicional
      description: Agrega cualquier otro contexto sobre el problema aqu铆