name: ❓ Question
description: Haz una pregunta sobre IssueFlow
title: "[Question]: "
labels: ["question", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        ¡Estamos aquí para ayudarte! 🤝
        
        Antes de hacer tu pregunta, por favor:
        - 📖 Revisa la [documentación](https://docs.issueflow.dev)
        - 🔍 Busca en [issues existentes](https://github.com/yosnap/issueflow/issues)
        - 💬 Considera preguntar en [Discord](https://discord.gg/issueflow) para respuestas más rápidas

  - type: dropdown
    id: category
    attributes:
      label: Categoría
      description: ¿Sobre qué es tu pregunta?
      options:
        - Setup e instalación
        - Configuración
        - Framework integration (React, Vue, etc.)
        - Integraciones (GitHub, ClickUp, etc.)
        - CLI tool
        - Troubleshooting
        - Best practices
        - Pricing y billing
        - Otro
    validations:
      required: true

  - type: textarea
    id: question
    attributes:
      label: Tu Pregunta
      description: Describe tu pregunta lo más claramente posible
      placeholder: "Me gustaría saber cómo..."
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Contexto
      description: Proporciona contexto adicional sobre tu situación
      placeholder: |
        - ¿Qué estás tratando de lograr?
        - ¿Qué has intentado hasta ahora?
        - ¿En qué entorno estás trabajando?

  - type: textarea
    id: environment
    attributes:
      label: Entorno (si es relevante)
      description: Información sobre tu setup técnico
      placeholder: |
        - OS: macOS/Windows/Linux
        - Framework: React/Vue/Next.js/etc.
        - IssueFlow version: x.x.x
        - Node.js version: x.x.x